


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import Sidebar from "@/components/shared/Sidebar";
import { Button } from "@/components/ui/button";
import { FileIcon, StarIcon } from "lucide-react";
import Link from "next/link";

export default function DashbordLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="container mx-auto pt-12 ">
      <div className="flex gap-8">
<Sidebar/>

        <div className="w-full">
          {children}
        </div>
      </div>
    </main>
  );
}
